model_name: camietagger
repo_id: Camais03/camie-tagger-v2
#static_thr: 0.6762319803237915 #[{float}]
dtype: bfloat16
batch_size: 64

###

#run_name: camie_nudenet
#dataset: nudenet
#val_split: validation[:50%]
#test_split: test
#sexy_policy: exclude #[unsafe, exclude]

run_name: camie_unsafebench
dataset: unsafebench
val_split: test
test_split: train

#run_name: camie_internal
#dataset: internal
#val_split: validation[:100%]
#test_split: test[:100%]

#run_name: camie_lspd_anime
#dataset: lspd
#lspd_domain: anime #"anime" | "normal" | "both"
#val_split: validation[95%:]
#test_split: test[:10%]