model_name: dinov3
model_id: facebookresearch/dinov3
model_entry: dinov3_vitl16_dinotxt_tet1280d20h24l
#static_thr: 0.526  # [float]
dtype: float16
batch_size: 96

###

#run_name: dinov3_vitl16_nudenet
#dataset: nudenet
#val_split: validation[:50%]
#test_split: test
#sexy_policy: exclude # [unsafe, exclude]

# run_name: dinov3_vitl16_unsafebench
# dataset: unsafebench
# val_split: test
# test_split: train

#run_name: dinov3_vitl16_internal
#dataset: internal
#val_split: validation[:100%]
#test_split: test[:100%]

#run_name: dinov3_vitl16_lspd_normal
#dataset: lspd
#lspd_domain: normal #"anime" | "normal" | "both"
#val_split: validation[95%:]
#test_split: test[:10%]
