model_name: florence2
model_id: microsoft/Florence-2-large
static_thr: 0.622459352016449
dtype: bfloat16
batch_size: 16

###

#run_name: florence2_large_nudenet
#dataset: nudenet
#val_split: validation[:50%]
#test_split: test
#sexy_policy: exclude # [unsafe, exclude]

#run_name: florence2_large_unsafebench
#dataset: unsafebench
#val_split: test
#test_split: train

#run_name: florence2_large_internal
#dataset: internal
#val_split: validation[:100%]
#test_split: test[:100%]

# run_name: florence2_large_lspd_normal
# dataset: lspd
# lspd_domain: normal #"anime" | "normal" | "both"
# val_split: validation[95%:]
# test_split: test[:10%]