model_name: siglip_lp
model_id: google/siglip-so400m-patch14-384
dtype: float16
batch_size: 80
pretrained: openai
l2norm: true
use_amp: true
linear_head_path: artifacts/siglip_nudenet_lp/linear_head.npz


# static_thr: 0.35302552580833435
#run_name: siglip_lp_nudenet
#dataset: nudenet
#sexy_policy: unsafe
#val_split: validation[:50%]
#test_split: test[:100%]

#run_name: siglip_lp_lspd_anime
#dataset: lspd
#lspd_domain: anime #"anime" | "normal" | "both"
#val_split: validation[95%:]
#test_split: test[:10%]

run_name: siglip_lp_nudenet
dataset: nudenet
#train_split: "train[:100%]"
val_split: "validation[:50%]"
test_split: "test[:100%]"
sexy_policy: exclude #[unsafe, exclude]


