model_name: wdtagger
repo_id: SmilingWolf/wd-eva02-large-tagger-v3
#static_thr: 0.5 #[{float}]
dtype: float16
batch_size: 80

###

#run_name: wd_eva02_tagger_nudenet
#dataset: nudenet
#val_split: validation[:50%]
#test_split: test
#sexy_policy: exclude #[unsafe, exclude]

run_name: wd_eva02_tagger_unsafebench
dataset: unsafebench
val_split: test
test_split: train

#run_name: wd_eva02_tagger_internal
#dataset: internal
#val_split: validation[:100%]
#test_split: test[:100%]

#run_name: wd_eva02_tagger_lspd_anime
#dataset: lspd
#lspd_domain: anime #"anime" | "normal" | "both"
#val_split: validation[95%:]
#test_split: test[:10%]

