model_name: wdtagger_trained
#static_thr: 0.9999997615814209 #[{float}]
dtype: float16
batch_size: 80
model_path: weights/wdeva02.pt
###

run_name: wdtagger_trained_unsafebench
dataset: unsafebench
val_split: test[:50%]
test_split: train
# sexy_policy: exclude #[unsafe, exclude]