model_name: clip_multilabel
#static_thr: 0.5 #[{float}]
dtype: float16
batch_size: 80
model_path: artifacts/clip_multilabel/outputs/head.pt
###

run_name: clip_multilabel_lp_nudenet
dataset: nudenet
val_split: validation[:50%]
test_split: test
sexy_policy: exclude #[unsafe, exclude]
