model_name: siglip
model_id: "google/siglip-so400m-patch14-384"
#static_thr: 0.868 #[{float}]
dtype: float16
batch_size: 80

###

run_name: siglip_so400m_nudenet
dataset: nudenet
#train_split: "train[:100%]"
val_split: validation[:50%]
test_split: test
sexy_policy: exclude #[unsafe, exclude]

#run_name: siglip_so400m_unsafebench
#dataset: unsafebench
#val_split: test[:100%]
#test_split: train[:100%]

#run_name: siglip_so400m_lspd_anime
#dataset: lspd
#lspd_domain: anime #"anime" | "normal" | "both"
#val_split: validation[95%:]
#test_split: test[:10%]

#run_name: siglip_so400m_internal
#dataset: internal
#val_split: validation[:100%]
#test_split: test[:100%]