model_name: wdtagger_trained
#static_thr: 0.9999997615814209 #[{float}]
dtype: float16
batch_size: 80
model_path: artifacts/wdeva02/best_test.pt
###

#run_name: wdtagger_trained_nudenet
#dataset: nudenet
#val_split: validation[:50%]
#test_split: test
#sexy_policy: unsafe #[unsafe, exclude]

#run_name: wdtagger_trained_unsafebench
#dataset: unsafebench
#val_split: test
#test_split: train

run_name: wdtagger_trained_nudenet
dataset: nudenet
val_split: validation[:50%]
test_split: test
sexy_policy: exclude #[unsafe, exclude]